{
 "title": "Solarshed Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarshed_battery_percentage" }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarshed_load_amperes" }
   ]
  },
  {
   "title": "Solar",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarshed_solar_amperes" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(solarshed_battery_temperature_celsius*1.8)+32"
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Battery Percentage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "solarshed_battery_percentage", "legendFormat": "Battery" }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "solarshed_load_power_watts", "legendFormat": "Watts" },
    { "expr": "solarshed_load_amperes", "legendFormat": "Amps" },
    { "expr": "solarshed_load_volts", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Solar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "solarshed_solar_watts", "legendFormat": "Watts" },
    { "expr": "solarshed_solar_amperes", "legendFormat": "Amps" },
    { "expr": "solarshed_solar_volts", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "(solarshed_battery_temperature_celsius*1.8)+32",
     "legendFormat": "Battery (F)"
    },
    {
     "expr": "solarshed_battery_temperature_celsius",
     "legendFormat": "Battery (C)"
    },
    {
     "expr": "solarshed_controller_temperature_celsius",
     "legendFormat": "Controller (C)"
    },
    {
     "expr": "(solarshed_controller_temperature_celsius*1.8)+32",
     "legendFormat": "Controller (F)"
    }
   ]
  }
 ]
}